### ISSUE TITLE
Internal Server Error when docker is up for longer period

### ISSUE THREAD

**Issue by svanimpelen** [whatdaybob/Custom_Docker_Images#33]
Everything seems to be working perfectly when the docker container has just been started. However, when after some time i try to do the call with postman to disable the guest. I get an internal server error. Trying to find out why i get it. However, when i restart the docker, everything works again

We had a chat on reddit, you indicated that it might have something to do with the worker and you are trying to implement multiple workers

**Comment by tk200** [comment]
Hi - I have the same issue. Was there ever a resolution, as this container is a brilliant idea, and solves a problem that Tado should implement as standard! Looking at the logs, when the issue occurs it states that there is an "error handling request":

[2021-07-30 11:21:59 +0000] [12] [ERROR] Error handling request /status
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 134, in handle
  self.handle_request(listener, req, client, addr)
File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
  respiter = self.wsgi(environ, resp.start_response)
File "falcon/api.py", line 274, in falcon.api.API.__call__
File "falcon/api.py", line 269, in falcon.api.API.__call__
File "/app/rest.py", line 32, in on_get
  status, message, geoTracking = tado.getGuestTracking()
File "/app/tado_guestmode.py", line 135, in wrapper
  return decorated(api, *args, **kwargs)
File "/app/tado_guestmode.py", line 172, in getGuestTracking
  status = requests.get(trackingurl, headers=self.params, timeout=10).json()['geoTrackingEnabled']
KeyError: 'geoTrackingEnabled'

Periodically, there is also a separate log entry and the config reloads - this resets the issue and no Internal Server Error is recieved:

[2021-07-30 11:22:51 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:12)
[2021-07-30 11:22:51 +0000] [12] [INFO] Worker exiting (pid: 12)
[2021-07-30 11:22:51 +0000] [13] [INFO] Booting worker with pid: 13
Configuration Found. Loading file.

**Comment by svanimpelen** [comment]
No, spoke to the dev but he was busy. The idea is great and if this get fixed i am sure a lot of people will use it.

**Comment by whatdaybob** [comment]
@svanimpelen @tk200 I have just pushed an update that will help hopefully. Please test and get back to me so I can update or close. Sorry about the wait on this one. Life, ha.

**Comment by tk200** [comment]
Thanks for your efforts looking at this. It’s been running for a couple of hours, and I’ve just had a ‘500 Internal Server Error’ - the logs are:

2022-02-21 12:33:07 | stdout | KeyError: 'geoTrackingEnabled'
2022-02-21 12:33:07 | stdout | status = requests.get(trackingurl, headers=self.params, timeout=10).json()['geoTrackingEnabled']
2022-02-21 12:33:07 | stdout | File "/app/tado_guestmode.py", line 168, in getGuestTracking
2022-02-21 12:33:07 | stdout | return decorated(api, *args, **kwargs)
2022-02-21 12:33:07 | stdout | File "/app/tado_guestmode.py", line 87, in wrapper
2022-02-21 12:33:07 | stdout | status, message, geoTracking = tado.getGuestTracking()
2022-02-21 12:33:07 | stdout | File "/app/rest.py", line 32, in on_get
2022-02-21 12:33:07 | stdout | File "falcon/app.py", line 361, in falcon.app.App.__call__
2022-02-21 12:33:07 | stdout | 2022-02-21 12:33:07 [FALCON] [ERROR] GET /status => Traceback (most recent call last):
2022-02-21 11:07:20 | stdout | respiter = self.wsgi(environ, resp.start_response)
2022-02-21 11:07:20 | stdout | /usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py:179: DeprecatedWarning: Call to deprecated property body. Please use text instead.
2022-02-21 11:04:22 | stdout | Configuration Found. Loading file.
2022-02-21 11:04:22 | stdout | [2022-02-21 11:04:22 +0000] [12] [INFO] Booting worker with pid: 12
2022-02-21 11:04:22 | stdout | [2022-02-21 11:04:22 +0000] [8] [INFO] Worker exiting (pid: 8)
2022-02-21 11:04:22 | stdout | [2022-02-21 11:04:22 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:8)
2022-02-21 11:03:22 | stdout | respiter = self.wsgi(environ, resp.start_response)
2022-02-21 11:03:22 | stdout | /usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py:179: DeprecatedWarning: Call to deprecated property body. Please use text instead.
2022-02-21 11:01:50 | stdout | respiter = self.wsgi(environ, resp.start_response)
2022-02-21 11:01:50 | stdout | /usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py:179: DeprecatedWarning: Call to deprecated property body. Please use text instead.
2022-02-21 11:01:49 | stdout | respiter = self.wsgi(environ, resp.start_response)
2022-02-21 11:01:49 | stdout | /usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py:179: DeprecatedWarning: Call to deprecated property body. Please use text instead.
2022-02-21 11:01:16 | stdout | respiter = self.wsgi(environ, resp.start_response)
2022-02-21 11:01:16 | stdout | /usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py:179: DeprecatedWarning: Call to deprecated property body. Please use text instead.
2022-02-21 11:00:52 | stdout | respiter = self.wsgi(environ, resp.start_response)
2022-02-21 11:00:52 | stdout | /usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py:179: DeprecatedWarning: Call to deprecated property body. Please use text instead.
2022-02-21 11:00:36 | stdout | Configuration Found. Loading file.
